"""
workflow/state.py
-----------------
Defines the shared state dictionary that flows through the WATCHDOG
LangGraph state machine.  Every agent node reads from and writes to
this state; LangGraph handles persistence and routing between nodes.

Using TypedDict (not a dataclass or Pydantic model) is the LangGraph
convention — it allows the framework to merge partial updates from each
node without requiring a full state object to be returned.
"""

from __future__ import annotations

from typing import List, TypedDict

from schemas.models import (
    CorrectionMandate,
    ExploitAssessment,
    FindingRecord,
    PatchProposal,
    ReviewVerdict,
    ThreatAssessment,
)


class WatchdogState(TypedDict):
    """
    Shared state for the WATCHDOG multi-agent pipeline.

    Fields
    ------
    target_path : str
        Absolute or relative path to the codebase / dependency tree being scanned.

    findings : List[FindingRecord]
        Raw security findings produced by the Scanner Agent (Bandit + custom AST rules).
        Populated during the ``scanner_agent`` node.

    assessments : List[ExploitAssessment]
        Deep exploit assessments produced by the Code Analyst Agent.
        Each assessment maps to one or more FindingRecord entries.

    threat_assessments : List[ThreatAssessment]
        Synthesised threat verdicts from the Threat Correlator Agent,
        combining code capability signals and maintainer trust signals.

    patches : List[PatchProposal]
        Remediation proposals generated by the Patch Writer Agent.

    verdicts : List[ReviewVerdict]
        Critic Agent verdicts on each PatchProposal.

    correction_mandates : List[CorrectionMandate]
        Structured correction instructions emitted when the Critic rejects a patch.
        Consumed by the Patch Writer on the next retry cycle.

    correction_count : int
        Running count of correction cycles completed.  Used to enforce the
        maximum retry limit (default: 2) in the conditional edge from
        ``reviewer`` back to ``patch_writer``.

    final_report : str
        The fully rendered security advisory Markdown/HTML string, produced by
        the Report Generator Agent as the final step.
    """

    target_path: str
    findings: List[FindingRecord]
    assessments: List[ExploitAssessment]
    threat_assessments: List[ThreatAssessment]
    patches: List[PatchProposal]
    verdicts: List[ReviewVerdict]
    correction_mandates: List[CorrectionMandate]
    correction_count: int
    final_report: str


def make_initial_state(target_path: str) -> WatchdogState:
    """
    Factory that returns a zeroed-out WatchdogState for a fresh pipeline run.

    Parameters
    ----------
    target_path : str
        Path to the project or dependency being scanned.

    Returns
    -------
    WatchdogState
        Initial state with empty lists and zero counters.
    """
    return WatchdogState(
        target_path=target_path,
        findings=[],
        assessments=[],
        threat_assessments=[],
        patches=[],
        verdicts=[],
        correction_mandates=[],
        correction_count=0,
        final_report="",
    )
